// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Types.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace ProtobufProto.Model
{

    [global::ProtoBuf.ProtoContract()]
    public enum TcpFlags
    {
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_REGESTER")]
        TcpRegester = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_LOGIN")]
        TcpLogin = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_LOGOUT")]
        TcpLogout = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_GET_PLAYER_TRANSFORMS")]
        TcpGetPlayerTransforms = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_CREATE_ROOM")]
        TcpCreateRoom = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_JOIN_ROOM")]
        TcpJoinRoom = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_LEAVE_ROOM")]
        TcpLeaveRoom = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_GET_ROOM_LIST")]
        TcpGetRoomList = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_GET_ROOM_USERS")]
        TcpGetRoomUsers = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_ROOM_READY")]
        TcpRoomReady = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_ROOM_CANCEL_READY")]
        TcpRoomCancelReady = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_ROOM_CHANGE_INDEX")]
        TcpRoomChangeIndex = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_DO_START_FIGHT")]
        TcpDoStartFight = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_CHECK_TIME")]
        TcpCheckTime = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_GET_USER_INFO")]
        TcpGetUserInfo = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_CHECK_VERSION")]
        TcpCheckVersion = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_ROOM_CHANGE")]
        TcpRoomChange = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_BROADCAST_METHOD")]
        TcpBroadcastMethod = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_BROADCAST_FIELD")]
        TcpBroadcastField = 18,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_UPDATE_TRANSFORM")]
        TcpUpdateTransform = 19,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_ROOM_MESSAGE")]
        TcpRoomMessage = 20,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_BD_CREATE_ROOM")]
        TcpBdCreateRoom = 21,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_BD_JOIN_ROOM")]
        TcpBdJoinRoom = 22,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_BD_LEAVE_ROOM")]
        TcpBdLeaveRoom = 23,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_ROOM_FIGHT")]
        TcpRoomFight = 24,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_BD_DO_START_FIGHT")]
        TcpBdDoStartFight = 25,
        [global::ProtoBuf.ProtoEnum(Name = @"TCP_GAME_FINISHED")]
        TcpGameFinished = 100,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum UdpFlags
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UDP_UP_FRAME")]
        UdpUpFrame = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"UDP_DOWN_FRAME")]
        UdpDownFrame = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"UDP_GAME_READY")]
        UdpGameReady = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"UDP_REQ_FRAME")]
        UdpReqFrame = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
