// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtobufProto.Model {

  /// <summary>Holder for reflection information generated from Types.proto</summary>
  public static partial class TypesReflection {

    #region Descriptor
    /// <summary>File descriptor for Types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtUeXBlcy5wcm90bxITUHJvdG9idWZQcm90by5Nb2RlbCriAwoIVGNwRmxh",
            "Z3MSEAoMVENQX1JFR0VTVEVSEAASDQoJVENQX0xPR0lOEAESDgoKVENQX0xP",
            "R09VVBACEh0KGVRDUF9HRVRfUExBWUVSX1RSQU5TRk9STVMQAxITCg9UQ1Bf",
            "Q1JFQVRFX1JPT00QBBIRCg1UQ1BfSk9JTl9ST09NEAUSEgoOVENQX0xFQVZF",
            "X1JPT00QBhIVChFUQ1BfR0VUX1JPT01fTElTVBAHEhYKElRDUF9HRVRfUk9P",
            "TV9VU0VSUxAIEhIKDlRDUF9ST09NX1JFQURZEAkSGQoVVENQX1JPT01fQ0FO",
            "Q0VMX1JFQURZEAoSGQoVVENQX1JPT01fQ0hBTkdFX0lOREVYEAsSFgoSVENQ",
            "X0RPX1NUQVJUX0ZJR0hUEAwSEgoOVENQX0NIRUNLX1RJTUUQDRIVChFUQ1Bf",
            "R0VUX1VTRVJfSU5GTxAOEhUKEVRDUF9DSEVDS19WRVJTSU9OEA8SEwoPVENQ",
            "X1JPT01fQ0hBTkdFEBASGAoUVENQX0JST0FEQ0FTVF9NRVRIT0QQERIXChNU",
            "Q1BfQlJPQURDQVNUX0ZJRUxEEBISGAoUVENQX1VQREFURV9UUkFOU0ZPUk0Q",
            "ExIVChFVRFBfR0FNRV9GSU5JU0hFRBBkKkQKCFVkcEZsYWdzEhAKDFVEUF9V",
            "UF9GUkFNRRAAEhIKDlVEUF9ET1dOX0ZSQU1FEAESEgoOVURQX0dBTUVfUkVB",
            "RFkQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProtobufProto.Model.TcpFlags), typeof(global::ProtobufProto.Model.UdpFlags), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///请求类型
  /// </summary>
  public enum TcpFlags {
    [pbr::OriginalName("TCP_REGESTER")] TcpRegester = 0,
    [pbr::OriginalName("TCP_LOGIN")] TcpLogin = 1,
    [pbr::OriginalName("TCP_LOGOUT")] TcpLogout = 2,
    [pbr::OriginalName("TCP_GET_PLAYER_TRANSFORMS")] TcpGetPlayerTransforms = 3,
    [pbr::OriginalName("TCP_CREATE_ROOM")] TcpCreateRoom = 4,
    [pbr::OriginalName("TCP_JOIN_ROOM")] TcpJoinRoom = 5,
    [pbr::OriginalName("TCP_LEAVE_ROOM")] TcpLeaveRoom = 6,
    [pbr::OriginalName("TCP_GET_ROOM_LIST")] TcpGetRoomList = 7,
    [pbr::OriginalName("TCP_GET_ROOM_USERS")] TcpGetRoomUsers = 8,
    [pbr::OriginalName("TCP_ROOM_READY")] TcpRoomReady = 9,
    [pbr::OriginalName("TCP_ROOM_CANCEL_READY")] TcpRoomCancelReady = 10,
    [pbr::OriginalName("TCP_ROOM_CHANGE_INDEX")] TcpRoomChangeIndex = 11,
    [pbr::OriginalName("TCP_DO_START_FIGHT")] TcpDoStartFight = 12,
    [pbr::OriginalName("TCP_CHECK_TIME")] TcpCheckTime = 13,
    [pbr::OriginalName("TCP_GET_USER_INFO")] TcpGetUserInfo = 14,
    [pbr::OriginalName("TCP_CHECK_VERSION")] TcpCheckVersion = 15,
    [pbr::OriginalName("TCP_ROOM_CHANGE")] TcpRoomChange = 16,
    [pbr::OriginalName("TCP_BROADCAST_METHOD")] TcpBroadcastMethod = 17,
    [pbr::OriginalName("TCP_BROADCAST_FIELD")] TcpBroadcastField = 18,
    [pbr::OriginalName("TCP_UPDATE_TRANSFORM")] TcpUpdateTransform = 19,
    /// <summary>
    ///UDP_Update_Turret_Direction = 16;
    ///Fire = 17;
    ///TakeDamage =18;
    ///Die = 19;
    ///RemainingTime =20;
    /// </summary>
    [pbr::OriginalName("UDP_GAME_FINISHED")] UdpGameFinished = 100,
  }

  public enum UdpFlags {
    [pbr::OriginalName("UDP_UP_FRAME")] UdpUpFrame = 0,
    [pbr::OriginalName("UDP_DOWN_FRAME")] UdpDownFrame = 1,
    [pbr::OriginalName("UDP_GAME_READY")] UdpGameReady = 2,
  }

  #endregion

}

#endregion Designer generated code
